<?php

namespace AdminBundle\Repository;

/**
 * PrdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrdRepository extends \Doctrine\ORM\EntityRepository
{
}
