<?php

namespace AdminBundle\Repository;

/**
 * ProduRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduRepository extends \Doctrine\ORM\EntityRepository
{
}
