<?php

namespace AdminBundle\Repository;

/**
 * RegistreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistreRepository extends \Doctrine\ORM\EntityRepository
{
}
